name: "Setup NodeJS and Install"
description: "Setup NodeJS & install dependencies"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version-file: package.json
    - name: Install dependencies
      shell: bash
      run: npm ci
