name: "Publish to NPM"
description: "Publish to NPM"

inputs:
  npm-token:
    description: The NPM access token to use when publishing
    required: true
  version-up:
    description: Version up
    default: "true"
    required: false
  version-tag:
    description: Version tag
    default: "pr"
    required: false
  directory:
    description: Directory
    default: "./"
    required: false
  label:
    description: Package label
    default: ""
    required: false

runs:
  using: composite
  steps:
    - name: Publish NPM
      if: inputs.version-up == 'false'
      working-directory: ${{ inputs.directory }}
      run: npm publish
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
    - name: Publish NPM (version up)
      if: >
        inputs.version-up == 'true'
        && (contains(env.LABELS, 'publish') || (inputs.label != '' && contains(env.LABELS, 'publish ' + inputs.label)))
      working-directory: ${{ inputs.directory }}
      run: >
        npm version prerelease --preid ${{ inputs.version-tag }}-${{ github.event.number }}-${{ env.SHORT_SHA }} --no-git-tag-version
        && npm publish --tag ${{ inputs.version-tag }}
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
        SHORT_SHA: $(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
        LABELS: ${{ github.event.pull_request.labels.*.name }}
