name: "Publish to NPM"
description: "Publish to NPM"

inputs:
  npm-token:
    description: The NPM access token to use when publishing
    required: true
  version-up:
    description: Version up
    default: "true"
    required: false
  directory:
    description: Directory
    default: "./"
    required: false

runs:
  using: composite
  steps:
    - name: Publish NPM
      if: inputs.version-up == 'false'
      working-directory: ${{ inputs.directory }}
      run: npm publish
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
    - name: Publish NPM (version up)
      if: inputs.version-up == 'true'
      working-directory: ${{ inputs.directory }}
      run: npm publish || (npm version prerelease --preid ${GITHUB_SHA::7} --no-git-tag-version && npm publish)
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
