name: "Publish to NPM"
description: "Publish to NPM"

inputs:
  npm-token:
    description: The NPM access token to use when publishing
    required: true
  npm-skip-version-up:
    description: Skip version up
    default: "false"
    required: false
  directory:
    description: Directory
    default: "./"
    required: false
  pr:
    description: If this is a PR
    default: "false"
    required: false
  pr-label:
    description: PR label for publish (publish {label})
    default: ""
    required: false
  pr-version-tag:
    description: Version tag for PR
    default: "pr"
    required: false

runs:
  using: composite
  steps:
    - name: Package version up
      if: inputs.npm-skip-version-up == 'false'
      working-directory: ${{ inputs.directory }}
      run: |
        PREFIX=""
        if [ "${{ inputs.pr }}" == "true" ]; then
          PREFIX="${{ inputs.pr-version-tag }}-${{ github.event.number }}-$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)"
        else
          PREFIX="${GITHUB_SHA::7}"
        fi
        npm version prerelease --preid "${PREFIX}" --no-git-tag-version
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
    - name: Publish
      if: >
        inputs.pr-only-labeled == 'false'
        || (contains(github.event.pull_request.labels.*.name, 'publish')
        || (inputs.pr-label != ''
        && contains(github.event.pull_request.labels.*.name, format('publish {0}', inputs.pr-label))))
      working-directory: ${{ inputs.directory }}
      run: |
        npm publish ${{ inputs.pr == 'true' && format('--tag {0}', inputs.pr-version-tag) || '' }}
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
