name: "Install Dependencies"
description: "Install npm dependencies"

inputs:
  npm-not-ci:
    description: "Run npm install instead of npm ci"
    default: "false"
    required: false
  npm-install-force:
    description: "Force npm install"
    default: "false"
    required: false

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: |
        CMD="npm"
        if [ "${{ inputs.npm-not-ci }}" = "true" ]; then
          CMD="${CMD} install"
        else
          CMD="${CMD} ci"
        fi

        if [ "${{ inputs.npm-install-force }}" = "true" ]; then
          CMD="${CMD} --force"
        fi

        ${CMD}
      shell: bash
