name: "Setup NodeJS"
description: "Setup NodeJS"

inputs:
  node-version:
    description: 'NodeJS version'
    default: '16.14.2'
    required: false

runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'