name: "Check Proto Library"

on:
  workflow_call:

jobs:
  proto-check:
    name: "Check Proto Library"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: valitydev/action-setup-thrift@v1
      - uses: valitydev/action-frontend/setup-install@v3
      - name: Build
        run: npm run codegen
